services:
  mail:
    restart: on-failure
    image: haravich/fake-smtp-server
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - devnet

  backend:
    image: template-backend:latest
    environment:
      DB_HOST: ${DB_HOST:?error}
      DB_PORT: ${DB_PORT:?error}
      DB_NAME: ${DB_NAME:?error}
      DB_SCHEMA: ${DB_SCHEMA:?error}
      DB_USER: ${DB_USER:?error}
      DB_PASSWORD: ${DB_PASSWORD:?error}
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - devnet

  migration:
    image: template-migration:latest
    environment:
      DB_HOST: ${DB_HOST:?error}
      DB_PORT: ${DB_PORT:?error}
      DB_NAME: ${DB_NAME:?error}
      DB_SCHEMA: ${DB_SCHEMA:?error}
      DB_USER: ${DB_USER:?error}
      DB_PASSWORD: ${DB_PASSWORD:?error}
    env_file:
      - .env
    networks:
      - devnet

  frontend:
    image: template-frontend:latest
    environment:
      API_URL: ${API_URL:?error}
      DB_HOST: ${DB_HOST:?error}
      DB_PORT: ${DB_PORT:?error}
      DB_NAME: ${DB_NAME:?error}
      DB_SCHEMA: ${DB_SCHEMA:?error}
      DB_USER: ${DB_USER:?error}
      DB_PASSWORD: ${DB_PASSWORD:?error}
      AUTH_SECRET: ${AUTH_SECRET:?error}
      AUTH_DISCORD_ID: ${AUTH_DISCORD_ID:?error}
      AUTH_DISCORD_SECRET: ${AUTH_DISCORD_SECRET:?error}
      AUTH_TRUST_HOST: true
      NEXT_PUBLIC_DOMAIN: ${NEXT_PUBLIC_DOMAIN:?error}
      SMTP_HOST: ${SMTP_HOST:?error}
      SMTP_PORT: ${SMTP_PORT:?error}
      SMTP_SECURE: ${SMTP_SECURE:?error}
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - devnet

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - template-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - devnet
    restart: unless-stopped

  pgadmin:
    image: elestio/pgadmin:REL-8_12
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - template-pgadmin:/var/lib/pgadmin
    ports:
      - "5050:5050"
    networks:
      - devnet
    restart: always

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?error}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?error}
      MINIO_BROWSER_REDIRECT: ${MINIO_BROWSER_REDIRECT:?error}
    env_file:
      - .env
    command: server --console-address ":9001" /data
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - devnet

  imgproxy:
    restart: unless-stopped
    image: darthsim/imgproxy:${IMGPROXY_TAG:-latest}
    healthcheck:
      test: ["CMD", "imgproxy", "health"]
      timeout: "10s"
      interval: "10s"
      retries: 3
    volumes:
      - ./www:/home:cached
    networks:
      - devnet
    ports:
      - "8080:8080"
    environment:
      ### Server
      ### See: https://docs.imgproxy.net/configuration/options#server
      IMGPROXY_NETWORK: "tcp"
      IMGPROXY_BIND: ":8080"

      ### Image sources
      ### See: https://docs.imgproxy.net/configuration/options#image-sources
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /home

      ### Debug
      ### See: https://docs.imgproxy.net/configuration/options#log
      IMGPROXY_LOG_LEVEL: "warn"
      IMGPROXY_LOG_FORMAT: "pretty"
      IMGPROXY_DEVELOPMENT_ERRORS_MODE: false
      IMGPROXY_ENABLE_DEBUG_HEADERS: false
      IMGPROXY_REPORT_DOWNLOADING_ERRORS: false

      ### Client
      IMGPROXY_READ_REQUEST_TIMEOUT: 10
      IMGPROXY_TIMEOUT: 10
      IMGPROXY_KEEP_ALIVE_TIMEOUT: 10
      IMGPROXY_CLIENT_KEEP_ALIVE_TIMEOUT: 90
      IMGPROXY_DOWNLOAD_TIMEOUT: 10
      IMGPROXY_BASE_URL: ""
      IMGPROXY_CACHE_CONTROL_PASSTHROUGH: false
      IMGPROXY_ETAG_BUSTER: ""
      IMGPROXY_HEALTH_CHECK_PATH: ""
      IMGPROXY_IGNORE_SSL_VERIFICATION: true
      IMGPROXY_MAX_CLIENTS: 2048
      IMGPROXY_MAX_REDIRECTS: 10
      IMGPROXY_PATH_PREFIX: ""
      IMGPROXY_REQUESTS_QUEUE_SIZE: 0
      IMGPROXY_SET_CANONICAL_HEADER: true
      IMGPROXY_SO_REUSEPORT: true
      IMGPROXY_TTL: 31536000
      IMGPROXY_USE_ETAG: false
      IMGPROXY_USE_LAST_MODIFIED: false

      ### Memory usage tweaks
      ### See: https://docs.imgproxy.net/configuration/options#memory-usage-tweaks
      IMGPROXY_FREE_MEMORY_INTERVAL: 10
      IMGPROXY_DOWNLOAD_BUFFER_SIZE: 0
      IMGPROXY_BUFFER_POOL_CALIBRATION_THRESHOLD: 1024

      ### Security
      ### See: https://docs.imgproxy.net/configuration/options#security
      IMGPROXY_ALLOW_LINK_LOCAL_SOURCE_ADDRESSES: false
      IMGPROXY_ALLOW_LOOPBACK_SOURCE_ADDRESSES: false
      IMGPROXY_ALLOW_PRIVATE_SOURCE_ADDRESSES: true
      IMGPROXY_ALLOW_SECURITY_OPTIONS: false
      IMGPROXY_MAX_ANIMATION_FRAME_RESOLUTION: 0
      IMGPROXY_MAX_ANIMATION_FRAMES: 64
      IMGPROXY_MAX_SRC_FILE_SIZE: 0
      IMGPROXY_MAX_SRC_RESOLUTION: 50
      IMGPROXY_MAX_SVG_CHECK_BYTES: 32768 # 32KB

      ### Cookies
      ### See: https://docs.imgproxy.net/configuration/options#cookies
      IMGPROXY_COOKIE_PASSTHROUGH: false
      IMGPROXY_COOKIE_BASE_URL: ""

      ### Compression
      ### See: https://docs.imgproxy.net/configuration/options#compression
      IMGPROXY_QUALITY: 80
      IMGPROXY_FORMAT_QUALITY: jpeg=80,webp=70,avif=50
      IMGPROXY_JPEG_PROGRESSIVE: false
      IMGPROXY_PNG_INTERLACED: false
      IMGPROXY_PNG_QUANTIZATION_COLORS: 256
      IMGPROXY_PNG_QUANTIZE: false
      IMGPROXY_AVIF_SPEED: 9
      IMGPROXY_ENABLE_AVIF_DETECTION: false
      IMGPROXY_ENFORCE_AVIF: false
      IMGPROXY_ENABLE_WEBP_DETECTION: false
      IMGPROXY_ENFORCE_WEBP: false

      ### Preferred formats
      ### See: https://docs.imgproxy.net/configuration/options#preferred-formats
      IMGPROXY_PREFERRED_FORMATS: jpeg,png,gif

      ### Skip processing
      ### https://docs.imgproxy.net/configuration/options#skip-processing
      IMGPROXY_SKIP_PROCESSING_FORMATS: "svg,webp,avif"

      ### Client Hints support
      ### See: https://docs.imgproxy.net/configuration/options#client-hints-support
      IMGPROXY_ENABLE_CLIENT_HINTS: true

      ### Presets
      ### See: https://docs.imgproxy.net/configuration/options#presets
      IMGPROXY_PRESETS: "default=resizing_type:fit/gravity:sm,logo=watermark:0.8:soea:20:20:0.15,repeated_logo=watermark:0.25:re:0:0:0.2"
      IMGPROXY_ONLY_PRESETS: false

      ### Miscellaneous
      ### See: https://docs.imgproxy.net/configuration/options#miscellaneous
      IMGPROXY_AUTO_ROTATE: true
      IMGPROXY_DISABLE_SHRINK_ON_LOAD: false
      IMGPROXY_ENFORCE_THUMBNAIL: false
      IMGPROXY_KEEP_COPYRIGHT: false
      IMGPROXY_RETURN_ATTACHMENT: false
      IMGPROXY_SANITIZE_SVG: true
      IMGPROXY_STRIP_COLOR_PROFILE: true
      IMGPROXY_STRIP_METADATA: true
      IMGPROXY_SVG_FIX_UNSUPPORTED: false
      IMGPROXY_USE_LINEAR_COLORSPACE: false

      # ### Amazon S3
      # ### See: https://docs.imgproxy.net/configuration/options#amazon-s3
      # IMGPROXY_USE_S3: false
      # IMGPROXY_S3_REGION: ""
      # IMGPROXY_S3_ENDPOINT: ""
      # IMGPROXY_S3_MULTI_REGION: false

networks:
  devnet:
    external: true

volumes:
  template-postgres:
  template-pgadmin:
