import { Box } from '@mui/material';
import type { Metadata } from 'next';
import { getTheme } from '@/features/theme/api/theme';
import { AuthProvider } from '@/features/auth/ui/AuthProvider';
import { MuiThemeProvider } from '@/features/theme/ui/MuiThemeProvider';
import { NextThemeProvider } from '@/features/theme/ui/NextThemeProvider';
import { NotificationProvider } from '@/features/notifications/ui/NotificationProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userTheme = await getTheme();

  return (
    <html lang="ru" suppressHydrationWarning>
      <AuthProvider>
        <Box
          component="body"
          sx={{
            display: 'flex',
            flexDirection: 'column',
            minHeight: '100vh',
          }}
        >
          <NextThemeProvider>
            <MuiThemeProvider theme={userTheme}>
              <NotificationProvider>{children}</NotificationProvider>
            </MuiThemeProvider>
          </NextThemeProvider>
        </Box>
      </AuthProvider>
    </html>
  );
}
