FROM node:alpine3.20 AS base

FROM base AS build

WORKDIR /app

COPY . .

RUN npm i

RUN npm run build --workspace=backend

FROM base AS main

WORKDIR /app

COPY --from=build /app/packages/db/migrations ./migrations

COPY --from=build /app/apps/backend/dist/migrator.js .

CMD ["node", "migrator.js"]