/**
 * @packageDocumentation
 * @module api.functional.api.v1.auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, IPropagation, Resolved } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

/**
 * @controller AuthController.authorize
 * @path POST /api/v1/auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function authorize(
  connection: IConnection,
): Promise<authorize.Output> {
  return !!connection.simulate
    ? authorize.simulate(connection)
    : PlainFetcher.propagate<any, any>(connection, {
        ...authorize.METADATA,
        template: authorize.METADATA.path,
        path: authorize.path(),
      });
}
export namespace authorize {
  export type Output = IPropagation<
    {
      201: boolean;
    },
    201
  >;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/auth",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/v1/auth";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<boolean> => typia.random<boolean>(g);
  export const simulate = (connection: IConnection): Output => {
    return {
      success: true,
      status: 201,
      headers: {
        "Content-Type": "application/json",
      },
      data: random(
        "object" === typeof connection.simulate && null !== connection.simulate
          ? connection.simulate
          : undefined,
      ),
    } as Output;
  };
}
