/**
 * @packageDocumentation
 * @module api.functional.api.v1.auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type {
  IConnection,
  IPropagation,
  Resolved,
  HttpError,
} from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

/**
 * @controller AuthController.authorize
 * @path POST /api/v1/auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function authorize(
  connection: IConnection,
  data: authorize.Input,
): Promise<authorize.Output> {
  typia.assert<typeof data>(data);
  return !!connection.simulate
    ? authorize.simulate(connection, data)
    : PlainFetcher.propagate<any, any>(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...authorize.METADATA,
          template: authorize.METADATA.path,
          path: authorize.path(),
        },
        data,
      );
}
export namespace authorize {
  export type Input = {
    sessionToken: string;
  };
  export type Output = IPropagation<
    {
      201: boolean;
    },
    201
  >;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/auth",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/v1/auth";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<boolean> => typia.random<boolean>(g);
  export const simulate = (
    connection: IConnection,
    data: authorize.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(data));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return {
      success: true,
      status: 201,
      headers: {
        "Content-Type": "application/json",
      },
      data: random(
        "object" === typeof connection.simulate && null !== connection.simulate
          ? connection.simulate
          : undefined,
      ),
    } as Output;
  };
}
